name: Deploy Python functions to AWS Lambda

on:
  push:
    branches:
      - 'main'
    paths:
      - 'lambda/boto3-get-all-inventory-items/lambda_function.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Zip the boto3-get-all-inventory-items Lambda function
        run: zip function.zip lambda_function.py
        working-directory: ./lambda/boto3-get-all-inventory-items
      - name: Update Lambda function code
        run: aws lambda update-function-code --function-name boto3-get-all-inventory-items --zip-file fileb://function.zip --publish
        working-directory: ./lambda/boto3-get-all-inventory-items
      - name: Cleanup boto3-get-all-inventory-items zip
        run: rm function.zip
        working-directory: ./lambda/boto3-get-all-inventory-items
